AppCodeFirstAssignment2020/Controllers/BarangController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace AppCodeFirstAssignment2020.Controllers
{
    public class BarangController : Controller
    {
        // GET: Barang
        public ActionResult Index()
        {
            return View();
        }

        //Get List Barang
        public ActionResult ListBarang()
        {
            return PartialView("_ListBarang",BarangRepo.All());
        }

        //Get Create Barang
        public ActionResult Create() 
        {
            BarangViewModel model = new BarangViewModel();
            //model.barang_id = DetailPenjualanRepo.NoNota();
            return PartialView("_Create", model);
        }

        [HttpPost]
        public ActionResult Create(BarangViewModel model)
        {
            ResponseResult result = BarangRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                massage = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }


        // GEt : Edit
        public ActionResult Edit(int id)
        {
            //id => Category Id
            return PartialView("_Edit", BarangRepo.ById(id));
        }
        [HttpPost]
        public ActionResult Edit(BarangViewModel model)
        {
            ResponseResult result = BarangRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

    }
}

AppCodeFirstAssignment2020/Controllers/DetailPenjualanController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel;

namespace AppCodeFirstAssignment2020.Controllers
{
    public class DetailPenjualanController : Controller
    {       
        // GET: DetailPenjualan
        public ActionResult Index()
        {
            return View();
        }
        
        //choose user admin
        public ActionResult Admin()
        {
            return PartialView();
        }

        //Get Menu Admin
        public ActionResult Menu()
        {
            return PartialView("_Menu");
        }

        //choose user customer
        public ActionResult Customer()
        {
            return PartialView();
        }

        // Get : list
        public ActionResult List()
        {
            return PartialView("_List", DetailPenjualanRepo.All());
        }


        // Get : Create
        public ActionResult Create()
        {
            DetailPenjualanViewModel model = new DetailPenjualanViewModel();
            model.no_nota = DetailPenjualanRepo.NoNota();
            return PartialView("_Create", model);
        }

        [HttpPost]
        public ActionResult Create(DetailPenjualanViewModel model)
        {
            ResponseResult result = DetailPenjualanRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                massage = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        // GEt : Edit
        public ActionResult Edit(int id)
        {
            //id => Category Id
            return PartialView("_Edit", DetailPenjualanRepo.ById(id));
        }
        [HttpPost]
        public ActionResult Edit(DetailPenjualanViewModel model)
        {
            ResponseResult result = DetailPenjualanRepo.Update(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        // Get : Delete
        public ActionResult Delete(int id)
        {
            return PartialView("_Delete", DetailPenjualanRepo.ById(id));
        }

        [HttpPost]
        public ActionResult Delete(DetailPenjualanViewModel model)
        {
            ResponseResult result = DetailPenjualanRepo.Delete(model);
            return Json(new
            {
                success = result.Success,
                message = result.Message,
                entity = result.Entity
            }, JsonRequestBehavior.AllowGet);
        }

        //Get Details
        public ActionResult Details(int id)
        {
            return PartialView("_Details", DetailPenjualanRepo.ById(id));
        }

        //Get Nota
        public ActionResult Nota(int id)
        {
            return PartialView("_Nota", DetailPenjualanRepo.DetailNota(id));
        }
    }
}

AppCodeFirstAssignment2020/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppCodeFirstAssignment2020.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AppCodeFirstAssignment2020/Controllers/PenjualanController.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppCodeFirstAssignment2020.Controllers
{
    public class PenjualanController : Controller
    {
        // GET: Penjualan
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Customer()
        {
            return PartialView("_Customer");
        }

        // Get : List Barang untuk beli
        public ActionResult ListShop()
        {
            return PartialView("_ListShop", PenjualanRepo.All());
        }

    }
}

AppCodeFirstAssignment2020/Views/Barang/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="navbar" style="background-color:white;">
    <div class="container">
        <h2 class="text-primary"><b><a href="@Url.Action("Index", "Home")">XSIS 2.0</a></b></h2>
    </div>
</div>

<div class="container center-block">

    <div class="nav navbar-btn col-md-3">
        <div class="btn-group-vertical">
            <input type="button" name="name" value="Admin" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-admin" />
            <input type="button" name="name" value="Customer" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-customer"/>
        </div>
    </div>
    <div class="body-content col-md-9">
        <div class="panel">

            <div class="panel-body" style="padding-top:0">
                <!-- Table -->
                <div id="data-list">
                    Pilih masuk sebagai admin atau customer!!!
                </div>

                <div class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content center-block" style="border:1px solid #337ab7">
                            <div class="modal-header" style="background:#337ab7;border-top-left-radius:5px;border-top-right-radius:5px;">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title">Model Title</h4>
                            </div>
                            <div class="modal-body" style="padding-bottom:0">
                                <p>One fine body&hellip;</p>
                            </div>
                        </div><!--modal-content-->
                    </div><!--modal-dialog-->
                </div><!--modal-->
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">        
        $(document).ready(function () {
            GetListBarang();
        });

        $("#btn-admin").click(function () {
            window.location.href = '@Url.Action("Index","Home")';
        });

        //$("#btn-detailPenjualan").click(function () {
        //GetList();
        //});

        //$("#btn-barang").click(function () {
        //GetListBarang();
        //});

        function GetMenu() {
            $.ajax({
                url: '@Url.Action("Menu","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        function GetList() {
            $.ajax({
                url: '@Url.Action("List","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        function GetListBarang() {
            $.ajax({
                url: '@Url.Action("ListBarang","Barang")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        $("#btn-customer").click(function () {
            window.location.href = '@Url.Action("Index","Penjualan")';
        });

        function GetListShop() {
            $.ajax({
                url: '@Url.Action("LishShop","Penjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        @*$("#btn-create-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Create New");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });*@
    </script>
}

AppCodeFirstAssignment2020/Views/Barang/_Edit.cshtml
@model ViewModel.BarangViewModel

@using (Html.BeginForm("Edit", "Barang", FormMethod.Post, new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BarangViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.barang_id)
        @*<div class="form-group">
                @Html.LabelFor(model => model.barang_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.barang_id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.barang_id, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.kode_barang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kode_barang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kode_barang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nama_barang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nama_barang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nama_barang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.satuan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.satuan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.satuan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.harga, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.harga, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.harga, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script type="text/javascript">
        $("#form-edit").submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    if (result.success) {
                        alert("Save successful!");
                        $(".modal").modal("hide");
                        GetListBarang();
                    } else {
                        alert("Error! " + result.message);
                    }
                }
            });
            return false;
        });
</script>

AppCodeFirstAssignment2020/Views/DetailPenjualan/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="navbar" style="background-color:white;">
    <div class="container">
        <h2 class="text-primary"><b><a href="@Url.Action("Index", "Home")">XSIS 2.0</a></b></h2>
    </div>
</div>

<div class="container center-block">

    <div class="nav navbar-btn col-md-3">
        <div class="btn-group-vertical">
            <input type="button" name="name" value="Admin" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-admin"/>
            <input type="button" name="name" value="Customer" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-customer"/>            
        </div>
    </div>
    <div class="body-content col-md-9">
        <div class="panel">            

            <div class="panel-body" style="padding-top:0">
                <!-- Table -->
                <div id="data-list">
                    Pilih masuk sebagai admin atau customer!!!
                </div>

                <div class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content center-block" style="border:1px solid #337ab7">
                            <div class="modal-header" style="background:#337ab7;border-top-left-radius:5px;border-top-right-radius:5px;">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title">Model Title</h4>
                            </div>
                            <div class="modal-body" style="padding-bottom:0">
                                <p>One fine body&hellip;</p>
                            </div>
                        </div><!--modal-content-->
                    </div><!--modal-dialog-->
                </div><!--modal-->
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList();
        });
        

        $("#btn-admin").click(function () {
            window.location.href = '@Url.Action("Index","Home")';
        });

        function GetMenu() {
            $.ajax({
                url: '@Url.Action("Menu","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        function GetList() {
            $.ajax({
                url: '@Url.Action("List","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        function GetListBarang() {
            $.ajax({
                url: '@Url.Action("ListBarang","Barang")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        $("#btn-customer").click(function () {
            window.location.href = '@Url.Action("Index","Penjualan")';
        });

        function GetListShop() {
            $.ajax({
                url: '@Url.Action("ListShop","Penjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        @*$("#btn-create-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Create New");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });*@
    </script>
}

AppCodeFirstAssignment2020/Views/DetailPenjualan/_Menu.cshtml
<input type="button" class="btn-primary" id="btn-barang" value="Barang"/>
<input type="button" class="btn-primary" id="btn-dataPenjualan" value="Data Penjualan"/>

<script type="text/javascript">
    $("#btn-dataPenjualan").click(function () {
        GetList();
    });

    $("#btn-barang").click(function () {
        @*var url = '@Url.Action("ListBarang", "Barang")';
        window.location.href = url;*@
        GetListBarang();
    });
</script>

AppCodeFirstAssignment2020/Views/Home/Index.cshtml
@*@{
        ViewBag.Title = "Home Page";
    }

    <div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@


@{
    ViewBag.Title = "Index";
}

<div class="navbar" style="background-color:white;">
    <div class="container">
        <h2 class="text-primary"><b><a href="@Url.Action("Index", "Home")">XSIS 2.0</a></b></h2>
    </div>
</div>

<div class="container center-block">

    <div class="nav navbar-btn col-md-3">
        <div class="btn-group-vertical">
            <input type="button" name="name" value="Admin" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-admin" />
            <input type="button" name="name" value="Customer" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-customer"/>
        </div>
    </div>
    <div class="body-content col-md-9">
        <div class="panel">

            <div class="panel-body" style="padding-top:0">
                <!-- Table -->
                <div id="data-list">
                    Pilih masuk sebagai admin atau customer!!!
                </div>

                <div class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content center-block" style="border:1px solid #337ab7">
                            <div class="modal-header" style="background:#337ab7;border-top-left-radius:5px;border-top-right-radius:5px;">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title">Model Title</h4>
                            </div>
                            <div class="modal-body" style="padding-bottom:0">
                                <p>One fine body&hellip;</p>
                            </div>
                        </div><!--modal-content-->
                    </div><!--modal-dialog-->
                </div><!--modal-->
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        //$(document).ready(function () {
        //    GetMenu();
        //});

        $("#btn-admin").click(function () {
        GetMenu();
        });

        function GetMenu() {
            $.ajax({
                url: '@Url.Action("Menu","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        function GetList() {
            @*$.ajax({
                url: '@Url.Action("Index","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });*@
            window.location.href = '@Url.Action("Index","DetailPenjualan")';
        };

        function GetListBarang() {
            @*$.ajax({
                url: '@Url.Action("Index","Barang")',
                type: 'get',
                success: function (result) {                    
                    $("#data-list").html(result);
                }
            });*@
            window.location.href = '@Url.Action("Index","Barang")';
        };

        $("#btn-customer").click(function () {            
            GetListShop();
            
        });

        function GetListShop() {
            @*$.ajax({
                url: '@Url.Action("Index","Penjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });*@
            window.location.href = '@Url.Action("Index","Penjualan")';
        };

        @*$("#btn-create-new").click(function () {
            $.ajax({
                url: '@Url.Action("Create","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $(".modal-title").html("Create New");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        });*@
    </script>
}

AppCodeFirstAssignment2020/Views/Penjualan/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="navbar" style="background-color:white;">
    <div class="container">
        <h2 class="text-primary"><b><a href="@Url.Action("Index", "Home")">XSIS 2.0</a></b></h2>
    </div>
</div>

<div class="container center-block">

    <div class="nav navbar-btn col-md-3">
        <div class="btn-group-vertical">
            <input type="button" name="name" value="Admin" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-admin" />
            <input type="button" name="name" value="Customer" class="col-sm-12 text-left form-control" style="margin-left:10px;background-color:white; border:1px solid blue;color:blue;" id="btn-customer" />
        </div>
    </div>
    <div class="body-content col-md-9">
        <div class="panel">

            <div class="panel-body" style="padding-top:0">
                <!-- Table -->
                <div id="data-list">
                    Pilih masuk sebagai admin atau customer!!!
                </div>

                <div class="modal fade" tabindex="-1" role="dialog">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content center-block" style="border:1px solid #337ab7">
                            <div class="modal-header" style="background:#337ab7;border-top-left-radius:5px;border-top-right-radius:5px;">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title">Model Title</h4>
                            </div>
                            <div class="modal-body" style="padding-bottom:0">
                                <p>One fine body&hellip;</p>
                            </div>
                        </div><!--modal-content-->
                    </div><!--modal-dialog-->
                </div><!--modal-->
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
         $(document).ready(function () {
            GetListShop();
        });


        $("#btn-admin").click(function () {
            window.location.href = '@Url.Action("Index","Home")';
        });

        function GetMenu() {
            $.ajax({
                url: '@Url.Action("Menu","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        function GetList() {
            $.ajax({
                url: '@Url.Action("Index","DetailPenjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        function GetListBarang() {
            $.ajax({
                url: '@Url.Action("Index","Barang")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };

        $("#btn-customer").click(function () {
            window.location.href = '@Url.Action("Index","Penjualan")';
        });

        function GetListShop() {
            $.ajax({
                url: '@Url.Action("ListShop","Penjualan")',
                type: 'get',
                success: function (result) {
                    $("#data-list").html(result);
                }
            });
        };


        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("Customer", "Penjualan")',
                type: 'get',
                success: function (result) {
                    $(".modal-content").addClass("modal-sm");
                    $(".modal-title").html("Masukan Nama");
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
            return false;
        });

        var name = ""; 
        var data = {};        
	$(".btn-order").click(function () {
		var list = [];		
		$("#data-approval tbody").find("tr").each(function () {
			var id = $(this).find("#id").val();
			var kode_barang = $(this).find("#client_id").val();
            var nama_barang = $(this).find("#placment_id").val();
            var check_box = $(this).find('input[id=check_box]').prop('checked');
            var Status = $(this).find('input[id=status]').val();
            var Timesheet_date = $(this).find('input[id=timesheet_date]').val();
            var Client_name = $(this).find('input[id=client_name]').val();
            var User_approval = btn;
            if (Check_box == true) {
                approv = {
                    id: Id,
                    client_id: Client_id,
                    placment_id: Placment_id,
                    check_box: Check_box,
                    status: Status,
                    timesheet_date: Timesheet_date,
                    client_name: Client_name,
                    user_approval: User_approval
            };
            //if(approv.Check_box == true) {
            TimeSheetApprovalViewModel.push(approv);
            //list.push(approv);
            //}
            };
        });
        //console.log(list);
		//console.log(TimeSheetApprovalViewModel);

		data = {
			id: $("#id").val(),
			client_id: $("#client_id").val(),
			placment_id: $("#placment_id").val(),
			check_box: $("#check_box").val(),
			status: $("#status").val(),
			timesheet_date: $("#timesheet_date").val(),
            client_name: $("#client_name").val(),
            target_result: 0,
            discipline: 0,
            competency: 0,
            Approval:TimeSheetApprovalViewModel
		}
		//$("#text").html(data);
		console.log(data);

        if (data.Approval != "") {
            $("#error-check_box").html("");
            //alert(data.Approval);
            $.ajax({
                url: '@Url.Action("Approval","TimeSheetApproval")',
                method: 'post',
                data: { model: data },
                success: function (result) {
                    //$(".modal-dialog").attr('class', 'modal-dialog modal-lg');
                    $(".modal-title").html("Penilaian Resource");
                    $(".modal-body").css('padding-top', '0');
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
            return false;
        }
        else {
            $("#error-check_box").html("*Centang minimal satu").css({ 'color': 'red', 'font-weight': 'unset' });
            return false;
        }
    });
    </script>
}